; ============================================================================
; Revision Number: 1003
; ============================================================================

[platformio]
default_envs = w35_espidf
boards_dir = boards

; ============================================================================
[env:w35_devel]
; ============================================================================
platform = espressif32@6.8.1
board = waveshare_esp32s3_3_5
framework = arduino

build_src_filter = -<*> +<../src/w35_devel/>

upload_port = COM3
monitor_port = COM3

board_build.partitions = default_16MB.csv
board_build.psram = enabled

monitor_speed = 115200

build_flags =
    -DLV_CONF_INCLUDE_SIMPLE

; ============================================================================
[env:w35_espidf]
; ============================================================================
platform = espressif32@6.8.1
board = waveshare_esp32s3_3_5
framework = espidf

build_src_filter = -<*> +<../src/w35_espidf/>

upload_port = COM3
monitor_port = COM3

board_build.partitions = default_16MB.csv
board_build.psram = enabled

monitor_speed = 115200